global using System;
global using System.Linq;
global using System.Collections.Generic;
global using Microsoft.Xna.Framework;
global using Microsoft.Xna.Framework.Graphics;
global using Microsoft.Xna.Framework.Input;
global using Engine;
global using Engine.Components;
global using Engine.Physics;